version: '3.8'
services:
  db2:
    build: .
    container_name: db2mock
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1-pwd
      DBNAME: SAMPLE
      TO_CREATE_SAMPLEDB: "true"
    ports:
      - "50000:50000"
    volumes:
      - ./sql:/database-init
    command: >
      /bin/bash -c "
      /opt/ibm/db2/bin/db2start &&
      db2 connect to SAMPLE &&
      for f in /database-init/*.sql; do db2 -tvf $f; done || true &&
      tail -f /dev/null
      "
