services:
  db2:
    image: icr.io/db2_community/db2
    container_name: db2mock
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1-pwd
      DBNAME: SAMPLE
    ports:
      - "50000:50000"      # Map host port 50000 to container port 50000
    volumes:
      - ./sql:/database-init
    command: /bin/bash -c "/opt/ibm/db2/bin/db2start && tail -f /dev/null"
